# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80fc13f8a4b786e0dbe0f6f3b30eb732fa2095d5d2b596797c5530cccd86a8e6d18122da8ff1a6064300218b5edaf8b846eea03465af0e742d41bbb216910238

test:
  secret_key_base: 6cf5910e02c83cfa1b0e1af89f2eaceba8fbf9776a91f1562cc2bbf521a20d5e0a37706dc81e8c19e77cbbe8d1bca12cd961e2e39fae93625e0e03f4262dbc1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
